# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: github-actions
run-name: ${{ github.actor }} runs codes
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "API Score client" #Must be unique in Heroku
          heroku_email: "valevi@hotmail.fr"
